### ISSUE TITLE
ライブラリフォルダ指定の重複

### ISSUE THREAD

**Issue by mursts** [mochan-tk/line-bot-python-sample#1]
下記のコードが``main.py``と``appengine_config.py``で重複していますよ
[公式ドキュメント](https://cloud.google.com/appengine/docs/python/tools/using-libraries-python-27)では``appengine_config.py``で指定すると書いてあります。

```python
from google.appengine.ext import vendor
vendor.add('lib')
```

**Comment by mochan-tk** [comment]
ありがとうございます。
ソースコードを参考にさせていただいた時に、appengine_config.pyで指定するのかぁと思って
消したつもりでいましたが残っていたんですね。。
ご指摘いただきまして、誠にありがとうございました^^
